[package]
name = "finder"
version = "0.1.0"
authors = ["Zhijian Huang <zjhuang.davis@gmail.com>"]

[dependencies]
toml = "0.4"
matches = "0.1.2"
serde_derive = "1.0"
serde = "1.0"
lazy_static = "0.2"


[lib]
crate-type = ["dylib"]
path = "src/lib.rs"
plugin = true
